# Generated by Django 3.1.2 on 2020-10-29 04:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicelevel',
            name='serviceDate',
        ),
        migrations.AddField(
            model_name='servicelevel',
            name='serviceRate',
            field=models.FloatField(null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(10)]),
        ),
    ]
